### ISSUE TITLE
legal: check copyrights, attribution and licencing

### ISSUE THREAD

**Issue by rzr** [rzr/pinball-table-hurd#2]
Relate-to: https://github.com/rzr/pinball/issues/4

Is @paolo-caroni the only author ?

Please edit debian/copyright to make sure nothing is left 

cc: @zezinho42

**Comment by paolo-caroni** [comment]
Hi, I'm the only author.
however part of files are "stealed" from tux table by Henrik Enqvist (see README).
In 2010 I was convinced that the HURD and GNU logos were distributable under GPLv2+, a more thorough check now made it clear that I was wrong.

**Comment by rzr** [comment]
Hi @paolo-caroni long time no see

May I request you to check my comments

https://github.com/rzr/pinball-table-hurd/pull/3

Then we can try to submit this table to debian (and derived)

**Comment by paolo-caroni** [comment]
Hi @rzr it's a very long time,
if you think that it's better specify exactly what file are released under what licence on debian/copyright I can divide it...
I'm simply lazy, so seems simple to me send to the README.txt file, but if for distribute under debian you need more specification... Ask me and I will rewrite debian/copyright.
cheers

**Comment by rzr** [comment]
well this is what debian's parser expects:

https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

you can check using lintian, if you dont use debian
you can run it with

docker build .

May @zezinho42 help for

https://github.com/rzr/pinball-table-gnu/issues/2

**Comment by rzr** [comment]
Please rebase on master I have just setup CI:

Check 1st log at:
https://travis-ci.com/rzr/pinball-table-hurd/builds/143638046

**Comment by paolo-caroni** [comment]
I think you are overestimating my computer skills, I'm in a nerd but a bad programmer and I'm not sure that I can be defined as such.
I have basic skills in C, I'm doing well with CAD drawing and thanks to this I have been able to draw the tables quite well.
Over the years I am improving, but honestly I did not understand what you asked me.
Do you want to delete my fork and redo a new one starting from your current "main"?

**Comment by rzr** [comment]
No problem let me explain what is rebasing check those hints:

https://purl.org/rzr/flows#

try in your repo:
```sh
git remote add upstream https://github.com/rzr/pinball-table-hurd
git fetch --all
git rebase -i remotes/upstream/master
git push -f
```

**Comment by rzr** [comment]
You can also names AUTHORS file and open a separate PR
I will merge it

**Comment by rzr** [comment]
https://github.com/rzr/pinball-table-hurd/pull/6/commits are gone ?

maybe you need to push debian copyrights over :
https://github.com/paolo-caroni/pinball-table-hurd/blob/patch-2/debian/copyright

Regards

**Comment by rzr** [comment]
Hi @paolo-caroni ,

As suggested in:

https://github.com/rzr/pinball-table-hurd/issues/5

Please add "AUTHORS" file , and close this issue I will release a version,
is it OK for you ?

Regards

**Comment by paolo-caroni** [comment]
The copyright is correct and complete, still missing Upstream Contact (https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#upstream-contact-field).
It seems to me that the Upstream-Contact are URIs to reach the project, so I think the better URI can be my mail or the URL here on github.
What do you think about it?

Cheers

**Comment by rzr** [comment]
well I think this repo is upstream so I can add it.

**Comment by rzr** [comment]
I think I am near to release, please confirm it's fine

Eventually add debian/upstream and add AUTHORS file and then I'll tag 0.0.YYYYMMDD and update debian packaging (from debian/master branch) 

Relate-to:  https://github.com/rzr/pinball-table-hurd/issues/5

**Comment by paolo-caroni** [comment]
For me it's fine, maybe Upstream-Contact: "paolo-caroni" can be "Paolo Caroni" in /debian/copyright.txt but honestly it's the same for me.
thank you :)

**Comment by rzr** [comment]
OK, I updated that file
so please close this ticket to acknowledge that legal requirements are fine.

If there is no change coming, I will release tomorrow

**Comment by paolo-caroni** [comment]
Maybe I'm blind, maybe I don't know well github... but seems to me that I can't close this issue since I haven't opened it.
I'm wrong?
For me is totally ok release tomorrow or when you have time.
Cheers,
Paolo

**Comment by rzr** [comment]
Ok sorry I can close it for you :)

I might update readme
