### ISSUE TITLE
publish in debian

### ISSUE THREAD

**Issue by rzr** [rzr/pinball-table-hurd#5]
I tried to build copyrights files but there are remaining issues to be fixed:

https://travis-ci.com/rzr/pinball-table-hurd/builds/143639851

W: pinball-table-hurd source: syntax-error-in-dep5-copyright line 38: Continuation line outside a paragraph (maybe line 37 should be " .").

@paolo-caroni ^ easy to fix then open PR on current base and I will merge it

E: pinball-table-hurd source: not-binnmuable-any-depends-all pinball-table-hurd -> pinball-table-hurd-data
W: pinball-table-hurd: wrong-bug-number-in-closes l3:#nnnn
W: pinball-table-hurd: new-package-should-close-itp-bug

I can do those ones

E: pinball-table-hurd: changelog-is-dh_make-template
W: pinball-table-hurd: spelling-error-in-description An other Another
E: pinball-table-hurd: non-empty-dependency_libs-in-la-file usr/lib/x86_64-linux-gnu/pinball/libModuleHurd.la
W: pinball-table-hurd: package-has-unnecessary-activation-of-ldconfig-trigger
W: pinball-table-hurd-data: wrong-bug-number-in-closes l3:#nnnn
W: pinball-table-hurd-data: new-package-should-close-itp-bug
E: pinball-table-hurd-data: changelog-is-dh_make-template

should be easy to fix too.

**Comment by paolo-caroni** [comment]
easy to fix how? I've rebuild repo on actual base, but I don't understand what file I have to modify ;)
line 37 and 38 but of what file?
I'm sorry...

**Comment by rzr** [comment]
Then open a PR I will show you inline

**Comment by rzr** [comment]
Hi 

I made some progress on:
https://github.com/rzr/pinball/issues/4

You can install hurd table without rebuilding from:

https://software.opensuse.org//download.html?project=home%3Arzrfreefr%3Asnapshot&package=pinball-table-hurd

What distros are you using? spec file could be added to this repo too.

**Comment by rzr** [comment]
Cross reference:

https://bugs.debian.org/948659#

**Comment by paolo-caroni** [comment]
> Hi
> 
> I made some progress on:
> [rzr/pinball#4](https://github.com/rzr/pinball/issues/4)
> 
> You can install hurd table without rebuilding from:
> 
> https://software.opensuse.org//download.html?project=home%3Arzrfreefr%3Asnapshot&package=pinball-table-hurd
> 
> What distros are you using? spec file could be added to this repo too.

I use Debian 10, so in theory it should work.
however if I add the repository it tells me that the Release.key signature is not valid.
If I download the package manually, it tells me that the pinball-table-hurd-data dependency is not satisfied.

**Comment by rzr** [comment]
yes it needs:

https://software.opensuse.org//download.html?project=home%3Arzrfreefr%3Asnapshot&package=pinball-table-hurd-data

Or try to use apt, it will resolve dependencies:


```
package=pinball-table-hurd

sudo sync
sudo apt-get update -y
sudo apt-get install -y base-files gnupg
cat /etc/os-release && . /etc/os-release
distro="${ID}_${VERSION_ID}"
[ "debian" != "${ID}" ] || distro="${distro}.0"
[ "debian_10.0" != "$distro" ] || distro="${ID}_${VERSION_ID}"
distro=$(echo "${distro}" | sed 's/.*/\u&/')
[ "ubuntu" != "${ID}" ] || distro="x${distro}"
url="http://download.opensuse.org/repositories/home:/rzrfreefr:/snapshot/${distro}"
file="/etc/apt/sources.list.d/home:rzrfreefr:snapshot.list"
curl -s ${url}/Release.key | gpg --with-fingerprint
curl ${url}/Release.key | sudo apt-key add -v -
echo "deb [allow-insecure=yes] $url /" | sudo tee "${file}"
curl "$url/Release.key" | sudo apt-key add -
sudo apt-get update -y
sudo apt-get install -y --allow-downgrades --allow-unauthenticated $package
```


Maybe I should  add this script somewhere (debian/install.sh ?)

**Comment by rzr** [comment]
hi @paolo-caroni I just fixed remaining lintian mistakes, only version should be set now
Any suggestion ? 

Since that table is already shipped into other distro, to avoid more confusion
I considered to use dates like 0.0.20200223 would that do the job ?

Also feel free to add "AUTHORS" file since you're the main creator.

Regards

Relate-to: https://bugs.debian.org/948659

**Comment by rzr** [comment]
Some new lintian warnings to fix:

https://mentors.debian.net/packages/uploader/rzr@users.sf.net

**Comment by rzr** [comment]
Update, I've asked for sponsorship at:
https://lists.debian.org/debian-devel-games/2020/04/msg00004.html

**Comment by rzr** [comment]
Update: I've asked for sponsorship elsewhere:

https://bugs.debian.org/959052

**Comment by rzr** [comment]
https://ftp-master.debian.org/new/pinball-table-hurd_0.0.20200312-1.html# #Pinball #Hurd table has been uploaded to #Debian , testers welcome

**Comment by rzr** [comment]
I am looking for debian developper that can upload this package:

https://mentors.debian.net/packages/uploader/rzr@users.sf.net/

Earlier version that @guimard  uploaded has some licensing issue, there are fixed now.

Feedback welcome:

https://purl.org/rzr/pinball

**Comment by guimard** [comment]
Pushed

**Comment by rzr** [comment]
It's published finally 

https://tracker.debian.org/pkg/pinball-table-hurd

Just in time for #MiniDebConfOnline:

https://purl.org/rzr/pinball

**Comment by rzr** [comment]
[2020-12-11] pinball-table-hurd 0.0.20201119-2 MIGRATED to testing (Debian testing watch) 

May this bug be commented on debian 11 release and other distros:

https://repology.org/project/pinball-table-hurd/history#

**Comment by rzr** [comment]
This can be closed, track next debian release:
https://wiki.debian.org/DebianBullseye

Meanwhile this table can be tested by booting debian images of pinball:

https://github.com/adoptware/pinball/releases/tag/0.3.20201218
