### ISSUE TITLE
Use new sounds

### ISSUE THREAD

**Issue by rzr** [rzr/pinball-table-hurd#8]
Reusing tux table was a good idea but maybe we can replace with other to make the table a bit more original.

I am sure there are many cool sounds shared as free licence online:

ie: 

https://freesound.org/browse/tags/game/

Feel free to link other sources  here

**Comment by rzr** [comment]
It would be nice to replace duplicated sounds:

https://dedup.debian.net/compare/pinball-data/pinball-table-hurd-data

**Comment by jgengelhardt** [comment]
I've gotten some copyleft sounds pulled together and have started testing.

**Comment by rzr** [comment]
thx please check https://github.com/adoptware/pinball-table-hurd/pull/12#issuecomment-1223802317
